---
# Ansible inventory for aipostex lab
all:
  vars:
    ansible_user: labadmin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    lab_root: "/home/{{ ansible_user }}/lab"
    repo_root: "{{ playbook_dir }}/../.."

  children:
    target_vms:
      hosts:
        ailab-dev:
          ansible_host: 172.16.50.10
          lab_role_dir: dev-workstation
        ailab-ml:
          ansible_host: 172.16.50.20
          lab_role_dir: ml-platform
        ailab-ds:
          ansible_host: 172.16.50.30
          lab_role_dir: data-sci
        ailab-app:
          ansible_host: 172.16.50.40
          lab_role_dir: app-platform

    attack_box:
      hosts:
        ailab-attack:
          ansible_host: 172.16.50.99
          lab_role_dir: attack-box
