#!/usr/bin/env bash
# provision-relay.sh — stand up the attendee ENTRANCE relay (WireGuard server + optional Tailscale
# subnet-router) with per-group firewall isolation. Run ON the relay host (root) — the estate attack
# box (.99) or a dedicated relay VM that can route into the lab bridges. See
# docs/deployment/connectivity.md. Consumes the artifacts from scripts/gen-attendee-access.sh.
#
# WHAT IT DOES (idempotent):
#   1. installs wireguard-tools; enables IPv4 forwarding
#   2. writes /etc/wireguard/wg0.conf from the generator's relay-server.key + relay-peers.conf,
#      with per-group FORWARD rules so tunnel 10.100.K.0/24 reaches ONLY estate 172.16.(50+K).0/24
#      (defence in depth — a client that lies about its AllowedIPs is still dropped here)
#   3. brings up wg-quick@wg0
#   4. optionally starts a Tailscale subnet-router advertising every estate /24
#
# NOTE: pauses-before-live-testing applies — validate on hardware before an event.
#
# Usage (on the relay, as root):
#   bash scripts/provision-relay.sh --groups 0,1,2 \
#        --server-key ./attendee-access/wireguard/relay-server.key \
#        --peers      ./attendee-access/wireguard/relay-peers.conf \
#        [--wg-port 51820] [--tunnel-base 10.100] [--tailscale --authkey tskey-...]
#
# Options:
#   --groups K,K,...   Estate group ids served by this relay (default 0)
#   --server-key FILE  Relay WG server PRIVATE key (from the generator)         [required]
#   --peers FILE       Server-side [Peer] blocks (from the generator)           [required]
#   --wg-port PORT     WireGuard UDP listen port (default 51820)
#   --tunnel-base A.B  WG tunnel /16 base (default 10.100 -> relay 10.100.0.1)
#   --tailscale        Also start a Tailscale subnet-router advertising the estate /24s
#   --authkey KEY      Tailscale auth key for --tailscale (or run `tailscale up` by hand)
#   --dry-run          Print the generated wg0.conf + commands; change nothing
set -eo pipefail

GROUP_IDS="0"           # NOTE: not GROUPS — that is a bash special read-only variable
SERVER_KEY=""
PEERS=""
WG_PORT=51820
TUNNEL_BASE="10.100"
DO_TS=0
TS_AUTHKEY=""
DRY_RUN=0

while [ $# -gt 0 ]; do
    arg="$1"; shift
    case "$arg" in
        --groups)      GROUP_IDS="$1"; shift ;;
        --server-key)  SERVER_KEY="$1"; shift ;;
        --peers)       PEERS="$1"; shift ;;
        --wg-port)     WG_PORT="$1"; shift ;;
        --tunnel-base) TUNNEL_BASE="$1"; shift ;;
        --tailscale)   DO_TS=1 ;;
        --authkey)     TS_AUTHKEY="$1"; shift ;;
        --dry-run)     DRY_RUN=1 ;;
        -h|--help)     sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "unknown arg: $arg" >&2; exit 2 ;;
    esac
done
GROUP_IDS="$(echo "$GROUP_IDS" | tr ',' ' ')"

[ -n "$SERVER_KEY" ] && [ -f "$SERVER_KEY" ] || { echo "[!] --server-key <relay-server.key> required" >&2; exit 2; }
[ -n "$PEERS" ] && [ -f "$PEERS" ] || { echo "[!] --peers <relay-peers.conf> required" >&2; exit 2; }
[ "$DRY_RUN" -eq 1 ] || [ "$(id -u)" = 0 ] || { echo "[!] run as root (or --dry-run)" >&2; exit 2; }

run() { if [ "$DRY_RUN" -eq 1 ]; then echo "  [dry-run] $*"; else eval "$*"; fi; }

# Estate subnet scheme (matches gen-attendee-access.sh). Proxmox: 172.16.(50+K); AWS: 10.0.(K+1).
estate_subnet() {
    case "${ESTATE_SCHEME:-proxmox}" in
        aws) echo "10.0.$(( $1 + 1 ))" ;;
        *)   echo "172.16.$(( 50 + $1 ))" ;;
    esac
}
# Broad supernet for the cross-estate catch-all DROP: Proxmox 172.16.0.0/16, AWS the VPC 10.0.0.0/16.
if [ "${ESTATE_SCHEME:-proxmox}" = aws ]; then
    ESTATE_SUPERNET="${ESTATE_SUPERNET:-10.0.0.0/16}"
else
    ESTATE_SUPERNET="${ESTATE_SUPERNET:-172.16.0.0/16}"
fi

# ── Build wg0.conf: [Interface] + per-group firewall in PostUp/PostDown, then the peers ─────────
priv="$(cat "$SERVER_KEY")"
postup=""; postdown=""
for K in $GROUP_IDS; do
    tun="${TUNNEL_BASE}.${K}.0/24"
    lab="$(estate_subnet "$K").0/24"
    # allow this group's tunnel -> ONLY its estate
    postup="${postup}iptables -A FORWARD -s ${tun} -d ${lab} -j ACCEPT; "
    postdown="${postdown}iptables -D FORWARD -s ${tun} -d ${lab} -j ACCEPT; "
done
# catch-all: any tunnel client -> any lab subnet that did NOT match above is DROPPED (cross-estate).
postup="${postup}iptables -A FORWARD -s ${TUNNEL_BASE}.0.0/16 -d ${ESTATE_SUPERNET} -j DROP; "
postdown="${postdown}iptables -D FORWARD -s ${TUNNEL_BASE}.0.0/16 -d ${ESTATE_SUPERNET} -j DROP; "

WG_CONF="$(cat <<EOF
# aipostex RTV attendee relay — generated by provision-relay.sh. Do not edit by hand.
[Interface]
Address = ${TUNNEL_BASE}.0.1/16
ListenPort = ${WG_PORT}
PrivateKey = ${priv}
# per-group isolation: tunnel 10.100.K.0/24 reaches ONLY its estate /24; everything else dropped.
PostUp = ${postup}
PostDown = ${postdown}

$(cat "$PEERS")
EOF
)"

if [ "$DRY_RUN" -eq 1 ]; then
    echo "=== /etc/wireguard/wg0.conf (dry-run) ==="; echo "$WG_CONF"
    echo "=== would also: enable ip_forward; systemctl enable --now wg-quick@wg0 ==="
    [ "$DO_TS" -eq 1 ] && echo "  [dry-run] tailscale up --advertise-routes=$(for K in $GROUP_IDS; do printf '%s.0/24,' "$(estate_subnet "$K")"; done | sed 's/,$//') ${TS_AUTHKEY:+--authkey ***}"
    exit 0
fi

# ── Install + enable ────────────────────────────────────────────────────────────────────────
command -v wg >/dev/null 2>&1 || run "apt-get update -qq && apt-get install -y -qq wireguard-tools"
# Persist to the standard drop-in so it survives a reboot / snapshot rollback (NOT /etc/sysctl.conf,
# which systemd-sysctl can override). Also apply immediately.
run "echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-lab-router.conf"
run "sysctl --system >/dev/null 2>&1 || sysctl -qw net.ipv4.ip_forward=1"

umask 077
run "mkdir -p /etc/wireguard"
printf '%s\n' "$WG_CONF" > /etc/wireguard/wg0.conf
echo "[+] wrote /etc/wireguard/wg0.conf ($(grep -c '^\[Peer\]' /etc/wireguard/wg0.conf) peers, groups: ${GROUP_IDS})"

run "systemctl enable wg-quick@wg0 >/dev/null 2>&1 || true"
# reload if already up (apply new peers/rules), else start
if systemctl is-active --quiet wg-quick@wg0; then
    run "wg syncconf wg0 <(wg-quick strip wg0) 2>/dev/null || systemctl restart wg-quick@wg0"
else
    run "systemctl start wg-quick@wg0"
fi
echo "[+] wg0 up on udp/${WG_PORT}"

# ── Optional Tailscale subnet-router ─────────────────────────────────────────────────────────
if [ "$DO_TS" -eq 1 ]; then
    routes="$(for K in $GROUP_IDS; do printf '%s.0/24,' "$(estate_subnet "$K")"; done | sed 's/,$//')"
    command -v tailscale >/dev/null 2>&1 || run "curl -fsSL https://tailscale.com/install.sh | sh"
    run "tailscale up --advertise-routes=${routes} --accept-routes=false ${TS_AUTHKEY:+--authkey ${TS_AUTHKEY}}"
    echo "[+] Tailscale advertising: ${routes}"
    echo "    Approve the routes in the admin console and apply tailscale-acl.json (tag -> route)."
fi

echo "[+] relay provisioned. Verify from a clean device (see docs/deployment/connectivity.md):"
echo "    connect -> reach ONLY your estate -> confirm a peer estate is blocked."
